# Change these first
owner: Skiddle-ID # Your GitHub organization or username, where this repository lives
repo: monitoring # The name of this repository

sites:
  - name: Main Website
    url: https://skiddle.id
    assignees:
      - arcestia
      
  - name: Private Wiki (wiki.skiddle.id)
    url: https://wiki.skiddle.id
    assignees:
      - arcestia
      
  # - name: Mail System
  #   url: https://email.skiddle.id
  #   assignees:
  #     - arcestia
      
  # - name: NTFY Services
  #   url: https://ntfy.skiddle.id
  #   assignees:
  #     - arcestia
      
  - name: Bluesky PDS
    url: https://pds.skiddle.id
    assignees:
      - arcestia
      
  # - name: Metrics Services
  #   url: $METRICS_API
  #   assignees:
  #     - arcestia
      
  # - name: CheckDomain API
  #   url: $CEKDOMAINAPI
  #   assignees:
  #     - arcestia
      
  # - name: Private Git
  #   url: https://git.skiddle.cloud
  #   assignees:
  #     - arcestia
      
  - name: Skiddle CDN
    url: $CDN_URL
    assignees:
      - arcestia
    expectedStatusCodes:
      - 200
      - 201
      - 400
      - 403
      - 404

  # SERVER PING
  # - name: GITHUB CI Nodes
  #   check: "tcp-ping"
  #   url: $GITCI_SERVER
  #   port: $PORT_CHECK
  #   assignees:
  #     - arcestia
      
  # - name: SG1 Nodes
  #   check: "tcp-ping"
  #   url: $IP_SG1
  #   port: $PORT_CHECK
  #   assignees:
  #     - arcestia
      
  # - name: SG2 Nodes
  #   check: "tcp-ping"
  #   url: $IP_SG2
  #   port: $SECRET_PORT
  #   assignees:
  #     - arcestia
      
  # - name: SG3 Nodes
  #   check: "tcp-ping"
  #   url: $IP_SG3
  #   port: $SECRET_PORT
  #   assignees:
  #     - arcestia
      
  # - name: DE1 Nodes
  #   check: "tcp-ping"
  #   url: $IP_DE1
  #   port: $SECRET_PORT
  #   assignees:
  #     - arcestia

  # - name: DE2 Nodes
  #   check: "tcp-ping"
  #   url: $IP_DE2
  #   port: $SECRET_PORT
  #   assignees:
  #     - arcestia

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: monitor.skiddle.id
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Skiddle Status Monitoring
  introTitle: "**Skiddle-ID** current network status. "
  introMessage: This page for Monitoring status of all Skiddle-ID Network.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

commitMessages:
  commitAuthorName: "skiddle-bot"
  commitAuthorEmail: "165562787+skiddle-bot@users.noreply.github.com"

skipDeleteIssues: true
      
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
