# Change these first
owner: Skiddle-ID # Your GitHub organization or username, where this repository lives
repo: monitoring # The name of this repository

sites:
  - name: Main Website
    url: https://skiddle.id
    assignees:
      - arcestia
      
  - name: Private Wiki (wiki.skiddle.id)
    url: https://wiki.skiddle.id
    assignees:
      - arcestia
      
  - name: Mail System
    check: "tcp-ping"
    url: $MAIL_SERVER
    port: $MAIL_PORT
    assignees:
      - arcestia
      
  - name: Skiddle API (Honolife API)
    url: https://api.skiddle.id
    assignees:
      - arcestia
      
  - name: Skiddle Vault
    url: https://vault.skiddle.id
    assignees:
      - arcestia
      
  - name: Skiddle Links
    url: https://skiddle.link
    assignees:
      - arcestia
      
  # - name: CheckDomain API
  #   url: $CEKDOMAINAPI
  #   assignees:
  #     - arcestia
      
  # - name: Private Git
  #   url: https://git.skiddle.cloud
  #   assignees:
  #     - arcestia
      
  - name: Skiddle CDN
    url: $CDN_URL
    assignees:
      - arcestia
    expectedStatusCodes:
      - 200
      - 201
      - 400
      - 403
      - 404

  # SERVER PING
  # - name: GITHUB CI Nodes
  #   check: "tcp-ping"
  #   url: $GITCI_SERVER
  #   port: $PORT_CHECK
  #   assignees:
  #     - arcestia

# Server SG (Singapore)
  - name: SG-1 Nodes
    check: "tcp-ping"
    url: $IP_SG1
    port: $PORT_SG1
    assignees:
      - skiddle-git
      - arcestia
      
  - name: SG-2 Nodes
    check: "tcp-ping"
    url: $IP_SG2
    port: $PORT_SG2
    assignees:
      - skiddle-git
      - arcestia
      
  - name: SG-3 Nodes
    check: "tcp-ping"
    url: $IP_SG3
    port: $PORT_SG3
    assignees:
      - skiddle-git
      - arcestia

  - name: SG-4 Nodes
    check: "tcp-ping"
    url: $IP_SG4
    port: $PORT_SG4
    assignees:
      - skiddle-git
      - arcestia

# Server ID (INDONESIA)      
  - name: ID-1 Nodes
    check: "tcp-ping"
    url: $IP_ID1
    port: $PORT_ID1
    assignees:
      - skiddle-git
      - arcestia

  - name: ID-2 Nodes
    check: "tcp-ping"
    url: $IP_ID2
    port: $PORT_ID2
    assignees:
      - skiddle-git
      - arcestia

  - name: ID-3 Nodes
    check: "tcp-ping"
    url: $IP_ID3
    port: $PORT_ID3
    assignees:
      - skiddle-git
      - arcestia

  - name: ID-4 Nodes
    check: "tcp-ping"
    url: $IP_ID4
    port: $PORT_ID4
    assignees:
      - skiddle-git
      - arcestia

  - name: ID-5 Nodes
    check: "tcp-ping"
    url: $IP_ID5
    port: $PORT_ID5
    assignees:
      - skiddle-git
      - arcestia

  - name: ID-6 Nodes
    check: "tcp-ping"
    url: $IP_ID6
    port: $PORT_ID6
    assignees:
      - skiddle-git
      - arcestia

  - name: ID-7 Nodes
    check: "tcp-ping"
    url: $IP_ID7
    port: $PORT_ID7
    assignees:
      - skiddle-git
      - arcestia

# Private IP
  - name: Internet Check
    url: $PRIVATE_IP
    check: "tcp-ping"
    port: $EXPOSE_PORT
    assignees:
      - skiddle-git
      - arcestia

  - name: CDN Nodes 1
    url: $CDN_1
    check: "tcp-ping"
    port: $EXPOSE_PORT
    assignees:
      - skiddle-git
      - arcestia

  - name: CDN Nodes 2
    url: $CDN_2
    check: "tcp-ping"
    port: $EXPOSE_PORT
    assignees:
      - skiddle-git
      - arcestia

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: monitor.skiddle.id
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Skiddle Status Monitoring
  introTitle: "**Skiddle-ID** current network status. "
  introMessage: This page for Monitoring status of all Skiddle-ID Network.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

commitMessages:
  commitAuthorName: "skiddle-bot"
  commitAuthorEmail: "165562787+skiddle-bot@users.noreply.github.com"

skipDeleteIssues: true

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
